version: '3'
services:

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    depends_on:
      - mongodb
    restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb:27017
  my-app:
    image: my-app:3.0
    container_name: 'my-app'
    depends_on:
      - mongodb
      - mongo-express
    ports:
      - 3000:3000
    environment: 
      -  MONGO_DB_USERNAME=admin
      -  MONGO_DB_PWD=password
    restart: always
    links:
      - mongodb

volumes:
  mongo-data:
    driver: local
